apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "windows-webserver.name" . }}
  namespace: {{ template "windows-webserver.namespace" . }}
  labels: {{ include "windows-webserver.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
