apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "windows-webserver.name" . }}
  namespace: {{ template "windows-webserver.namespace" . }}
  labels: {{ include "windows-webserver.labels" . | nindent 4 }}
    app: {{ template "windows-webserver.name" . }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
